# Generated by Django 2.0.7 on 2018-07-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='search_string',
            field=models.CharField(default='a movie title', max_length=200),
        ),
    ]
