# Generated by Django 2.0.7 on 2018-07-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_search_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='box_office',
            new_name='boxoffice',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_id',
            new_name='imdbid',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_rating',
            new_name='imdbrating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_votes',
            new_name='imdbvotes',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='search_string',
            new_name='searchstring',
        ),
    ]
